name: "greetings"
description: "Greet users"

inputs:
 username: 
   default: Mahendra
   description: "Name of User"
   required: true

runs:
  using: composite
  steps:
  - uses: actions/checkout@v6
  - run: "Hello, $INPUTS_USERNAME, welcome to Actions !"
    shell: bash
    
